spring:
    application:
        name: StorageService
    datasource:
        url: jdbc:sqlite:db_file.db
        driverClassName: org.sqlite.JDBC
        username: sa
        password: sa
    jpa:
        database-platform: org.hibernate.dialect.SQLiteDialect
        hibernate:
            ddl-auto: none